version: '3.8'

services:
  db:
    image: postgres:13.2
    ports:
      - "5432:5432"
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "postgres" ]
      interval: 1s
      retries: 20
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  web:
    build: .
    command: scripts/startup.sh
    volumes:
      - "./:/code"
    ports:
      - "8000:8000"
    env_file:
      - config/.env

#networks:
#  sirius:
#    external: true
