services:
  db:
    image: postgres:13.2
    ports:
      - "5432:5432"
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "postgres" ]
      interval: 1s
      retries: 20
    env_file:
      - config/.env.db

#services:
#  db:
#    image: postgres:latest
#    ports:
#      - "${DB_PORT}:5432"
#    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
#    healthcheck:
#      test: [ "CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}" ]
#      interval: 1s
#      retries: 20
#    env_file:
#      - config/.env
#    environment:
#      POSTGRES_DB: ${DB_NAME}
#      POSTGRES_USER: ${DB_USER}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}


#  consumer:
#    build: .
#    command: scripts/startup.sh
#    volumes:
#      - "./:/code"
#    ports:
#      - "8000:8000"
#    env_file:
#      - config/.env

  rabbitmq:
    image: rabbitmq:3.13.7-management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:6.2.4
    ports:
      - "6379:6379"

#networks:
#  sirius:
#    external: true
