services:
  db:
    image: postgres:13.2
    ports:
      - "5432:5432"
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "postgres" ]
      interval: 1s
      retries: 20
    env_file:
      - config/.env.db

#  consumer:
#    build: .
#    command: scripts/startup.sh
#    volumes:
#      - "./:/code"
#    ports:
#      - "8000:8000"
#    env_file:
#      - config/.env

  rabbitmq:
    image: rabbitmq:3.13.7-management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:6.2.4
    ports:
      - "6379:6379"

  minio:
    hostname: ${MINIO_HOST}
    image: quay.io/minio/minio:RELEASE.2024-11-07T00-52-20Z
    command: server /data --console-address ":9001"
    container_name: acquaintance-minio
    volumes:
      - /minio/data:/minio_data
    ports:
      - "9000:9000"
    env_file:
      - config/.env.minio
