version: '3.8'

services:
#  db:
#    image: postgres:13.2
#    ports:
#      - "5432:5432"
#    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
#    healthcheck:
#      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "postgres" ]
#      interval: 1s
#      retries: 20
#    environment:
#      POSTGRES_DB: "postgres"
#      POSTGRES_USER: "postgres"
#      POSTGRES_PASSWORD: "postgres"
#    volumes:
#      - "./:/code"
#    networks:
#      - "sirius"

  web:
    build: .
    command: python3 -m uvicorn src.app:create_app --factory --host 0.0.0.0
    volumes:
      - "./:/code"
    ports:
      - "8000:8000"

#networks:
#  sirius:
#    external: true
