"""Initial database

Revision ID: 77d16ce68149
Revises: 
Create Date: 2026-04-24 01:57:45.595541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77d16ce68149'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_scheduled_reservation_jobs_run_at', table_name='scheduled_reservation_jobs')
    op.drop_table('scheduled_reservation_jobs')
    op.drop_constraint('fk_application_forms_user_id_users', 'application_forms', type_='foreignkey')
    op.create_foreign_key(op.f('fk_application_forms_user_id_users'), 'application_forms', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint('fk_reservations_room_id_rooms', 'reservations', type_='foreignkey')
    op.drop_constraint('fk_reservations_user_id_users', 'reservations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_reservations_user_id_users'), 'reservations', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_reservations_room_id_rooms'), 'reservations', 'rooms', ['room_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reservations_room_id_rooms'), 'reservations', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_reservations_user_id_users'), 'reservations', schema='public', type_='foreignkey')
    op.create_foreign_key('fk_reservations_user_id_users', 'reservations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_reservations_room_id_rooms', 'reservations', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_application_forms_user_id_users'), 'application_forms', schema='public', type_='foreignkey')
    op.create_foreign_key('fk_application_forms_user_id_users', 'application_forms', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_table('scheduled_reservation_jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reservation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('run_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('job_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='scheduled_reservation_jobs_pkey')
    )
    op.create_index('idx_scheduled_reservation_jobs_run_at', 'scheduled_reservation_jobs', ['run_at'], unique=False)
    # ### end Alembic commands ###
