version: 1
disable_existing_loggers: no
formatters:
  console_formatter_backend:
    (): src.logger.ConsoleFormatter
  console_formatter_start_consumer:
    (): consumers.start_consumer.logger.ConsoleFormatter
  console_formatter_registration_consumer:
    (): consumers.registration_consumer.logger.ConsoleFormatter
  console_formatter_application_form_consumer:
    (): consumers.application_form_consumer.logger.ConsoleFormatter
handlers:
  console_handler_backend:
    class: logging.StreamHandler
    formatter: console_formatter_backend
  console_handler_start_consumer:
    class: logging.StreamHandler
    formatter: console_formatter_start_consumer
  console_handler_registration_consumer:
    class: logging.StreamHandler
    formatter: console_formatter_registration_consumer
  console_handler_application_form_consumer:
    class: logging.StreamHandler
    formatter: console_formatter_application_form_consumer
root:
  level: INFO
  handlers: [console_handler_backend]
loggers:
  'backend_logger':
    level: INFO
    propagate: no
    handlers: [console_handler_backend]
  'start_consumer_logger':
    level: INFO
    propagate: no
    handlers: [console_handler_start_consumer]
  'registration_consumer_logger':
    level: INFO
    propagate: no
    handlers: [ console_handler_registration_consumer ]
  'application_form_consumer_logger':
    level: INFO
    propagate: no
    handlers: [ console_handler_application_form_consumer ]
  'uvicorn':
    level: INFO
    propagate: no
