START = '/start'
GET_MY_TELEGRAM_ID = '/get_my_telegram_id'
CREATE_RESERVATION = '/create_reservation'
CONFIRM_RESERVATION = '/confirm_reservation'
ADD_APPLICATION_FORM = '/add_application_form'
CHECK_MY_RESERVATION = '/check_my_reservation'
CHECK_MY_RESERVATIONS_ARCHIVE = '/check_my_reservations_archive'
DELETE_RESERVATION = '/delete_reservation'

HIRE_REPAIRMAN = '/hire_repairman'
FIRE_REPAIRMAN = '/fire_repairman'
ADMIN_STATS = '/check_stats'
REPAIRMAN_STATS = '/check_my_stats'
